services:
  db:
    image: postgres
    container_name: database
    environment:
      POSTGERS_DB: my_postgres
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"
    volumes:
      - script_db:/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - script_net

  base_script:
    build: .
    container_name: base_script
    depends_on:
      - db
    environment:
      HOST: database
      DB_NAME: my_postgres
      DB_USERNAME: test_user
      DB_PASSWORD: test1234
      PORT: 5432
    networks:
      - script_net
    volumes:
      - .:/app
    command: python task_7.py


volumes:
  script_db:
    name: script_db

networks:
  script_net:
    name: script_net
