services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: my_postgres
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"
    volumes:
      - script_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - script_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--fail", "-U", "test_user"]
      interval: 5s
      timeout: 5s
      retries: 3
      
  base_script:
    build: .
    container_name: base_script
    depends_on:
      db:
        condition: service_healthy    
    environment:
      DB_HOST: db
      DB_NAME: my_postgres
      DB_USER: test_user
      DB_PASSWORD: test1234
      DB_PORT: 5432
    networks:
      - script_net
    volumes:
      - .:/app
    command: python -u task_7.py 


volumes:
  script_db:

networks:
  script_net:
    name: script_net
