version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres
    secrets:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - script_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - script_net
    restart: always
    healthcheck:
      test: pg_isready -d my_postgres -U test_user
      interval: 1s
      timeout: 5s
      retries: 10
      

  base_script:
    build: .
    container_name: base_script
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/scripts_connect_data
    secrets:
      - scripts_connect_data   
    networks:
      - script_net
    volumes:
      - .:/app
    user: "test_user"  
    command: python3 -u -m task_7

volumes:
  script_db:

networks:
  script_net:
    name: script_net
