services:
  db:
    image: postgres
    environment:      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}      
    ports:
      - "5432:5432"
    volumes:
      - script_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - script_net
    restart: always
    healthcheck:
      test: pg_isready -d my_postgres -U test_user
      interval: 1s
      timeout: 5s
      retries: 10
      

  base_script:
    build: .
    container_name: base_script
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - script_net
    volumes:
      - .:/app
    user: "test_user"  
    command: python3 -u -m main

volumes:
  script_db:

networks:
  script_net:
    name: script_net
