version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: my_postgres      
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"
    volumes:
      - script_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - script_net
    restart: always
    healthcheck:
      healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10

  base_script:
    build: .
    container_name: base_script
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: my_postgres
      DB_USER: test_user
      DB_PASSWORD: test1234
      DB_PORT: 5432
    networks:
      - script_net
    volumes:
      - .:/app
    user: "test_user"  # Запуск от имени пользователя test_user
    command: python3 -u -m task_7  # Убрано .py, так как используется -m

volumes:
  script_db:

networks:
  script_net:
    name: script_net
